const MLC = require('../../helpers/mlc')
const { COMMAND_ADMIN_TEXT, COMMAND_CURRENT_TEXT, COMMAND_HELP_TEXT, COMMAND_BROADCAST_TEXT } = require('./messages')

exports.MLC_HELP = MLC(COMMAND_HELP_TEXT)
exports.MLC_CURRENT = MLC(COMMAND_CURRENT_TEXT)
exports.MLC_BROADCAST = MLC(COMMAND_BROADCAST_TEXT)
exports.MLC_ADMIN = MLC(COMMAND_ADMIN_TEXT)
