exports.backKeyboard = require('./back')
exports.confirmInline = require('./confirmInline')
exports.coreKeyboard = require('./core')
exports.adminKeyboard = require('./admin')
exports.helpInline = require('./helpInline')
exports.editAdminListInline = require('./editAdminListInline')
exports.addAdminInline = require('./addAdminInline')
