const MLC = require('../../helpers/mlc')
const {
  COMMAND_HELP_ADMIN_TEXT,
  COMMAND_HELP_BOT_TEXT,
  COMMAND_HELP_BROADCAST_TEXT,
  COMMAND_HELP_GAME_TEXT,
} = require('./messages')

exports.MLC_HELP_BOT = MLC(COMMAND_HELP_BOT_TEXT)
exports.MLC_HELP_GAME = MLC(COMMAND_HELP_GAME_TEXT)
exports.MLC_HELP_BROADCAST = MLC(COMMAND_HELP_BROADCAST_TEXT)
exports.MLC_HELP_ADMIN = MLC(COMMAND_HELP_ADMIN_TEXT)
