const {
  COMMAND_HELP,
  COMMAND_ADMIN,
  COMMAND_HELP_ADMIN,
  COMMAND_HELP_BOT,
  COMMAND_HELP_FOLLOW,
  COMMAND_HELP_GAME,
} = require('./commands')

exports.ACTION_CONFIRM = 'confirm'
exports.ACTION_CANCEL = 'cancel'

exports.ACTION_HELP = `${COMMAND_HELP}_${COMMAND_HELP}`
exports.ACTION_HELP_ADMIN = `${COMMAND_HELP}_${COMMAND_HELP_ADMIN}`
exports.ACTION_HELP_BOT = `${COMMAND_HELP}_${COMMAND_HELP_BOT}`
exports.ACTION_HELP_FOLLOW = `${COMMAND_HELP}_${COMMAND_HELP_FOLLOW}`
exports.ACTION_HELP_GAME = `${COMMAND_HELP}_${COMMAND_HELP_GAME}`

exports.ACTION_ADMIN_ADD = `${COMMAND_ADMIN}_add`
exports.ACTION_ADMIN_REMOVE = `${COMMAND_ADMIN}_remove`
exports.ACTION_ADMIN_EDIT_CONFIRM_S = `${COMMAND_ADMIN}_edit_confirm_s` // С возможностью добавлять.удалять админов
