const MLC = require('../helpers/mlc')
const {
  COMMAND_BACK_TEXT,
  COMMAND_HOME_TEXT,
  COMMAND_ADMIN_TEXT,
  COMMAND_CURRENT_TEXT,
  COMMAND_FOLLOW_TEXT,
  COMMAND_HELP_TEXT,
  COMMAND_ADMIN_LIST_TEXT,
  COMMAND_ADMIN_ADD_TEXT,
  COMMAND_ADMIN_REMOVE_TEXT,
  COMMAND_ADMIN_FEATURES_TEXT,
  COMMAND_ADMIN_CARDS_TEXT,
  COMMAND_ADMIN_TIMINGS_TEXT,
} = require('../messages/commands')

exports.MLC_BACK = MLC(COMMAND_BACK_TEXT)
exports.MLC_HOME = MLC(COMMAND_HOME_TEXT)

exports.MLC_HELP = MLC(COMMAND_HELP_TEXT)
exports.MLC_CURRENT = MLC(COMMAND_CURRENT_TEXT)
exports.MLC_FOLLOW = MLC(COMMAND_FOLLOW_TEXT)
exports.MLC_ADMIN = MLC(COMMAND_ADMIN_TEXT)

// ADMIN
exports.MLC_ADMIN_LIST = MLC(COMMAND_ADMIN_LIST_TEXT)
exports.MLC_ADMIN_ADD = MLC(COMMAND_ADMIN_ADD_TEXT)
exports.MLC_ADMIN_REMOVE = MLC(COMMAND_ADMIN_REMOVE_TEXT)
exports.MLC_ADMIN_FEATURES = MLC(COMMAND_ADMIN_FEATURES_TEXT)
exports.MLC_ADMIN_CARDS = MLC(COMMAND_ADMIN_CARDS_TEXT)
exports.MLC_ADMIN_TIMINGS = MLC(COMMAND_ADMIN_TIMINGS_TEXT)
