const MLC = require('../helpers/mlc')
const { COMMAND_ADMIN_TEXT, COMMAND_CURRENT_TEXT, COMMAND_FOLLOW_TEXT, COMMAND_HELP_TEXT } = require('../messages/commands')

exports.MLC_HELP = MLC(COMMAND_HELP_TEXT)
exports.MLC_CURRENT = MLC(COMMAND_CURRENT_TEXT)
exports.MLC_FOLLOW = MLC(COMMAND_FOLLOW_TEXT)
exports.MLC_ADMIN = MLC(COMMAND_ADMIN_TEXT)
