const { COMMAND_HELP_BOT, COMMAND_HELP_ADMIN, COMMAND_HELP_FOLLOW, COMMAND_HELP_GAME } = require('../../constants/commands')
const getHelpBot = require('../../messages/help/bot')
const getHelpGame = require('../../messages/help/game')
const getHelpFollow = require('../../messages/help/follow')
const getHelpAdmin = require('../../messages/help/admin')
const sendAnswer = require('./sendAnswer')

exports.helpGameDetails = ctx => sendAnswer(ctx, getHelpGame, COMMAND_HELP_GAME)
exports.helpBotDetails = ctx => sendAnswer(ctx, getHelpBot, COMMAND_HELP_BOT)
exports.helpFollowDetails = ctx => sendAnswer(ctx, getHelpFollow, COMMAND_HELP_FOLLOW)
exports.helpAdminDetails = ctx => sendAnswer(ctx, getHelpAdmin, COMMAND_HELP_ADMIN)
