const MLC = require('../../helpers/mlc')
const {
  COMMAND_ADMIN_FEATURE_TEXT,
  COMMAND_ADMIN_CARDS_TEXT,
  COMMAND_ADMIN_TIMINGS_TEXT,
  COMMAND_ADMIN_LIST_TEXT,
} = require('./messages')

exports.MLC_ADMIN_FEATURE = MLC(COMMAND_ADMIN_FEATURE_TEXT)
exports.MLC_ADMIN_CARDS = MLC(COMMAND_ADMIN_CARDS_TEXT)
exports.MLC_ADMIN_TIMINGS = MLC(COMMAND_ADMIN_TIMINGS_TEXT)
exports.MLC_ADMIN_LIST = MLC(COMMAND_ADMIN_LIST_TEXT)
